version: '3'

services:
  postgres-test-db:
    image: postgres:latest
    # network_mode: host
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=entersecretpassword
    volumes:
      - pg-test-database:/var/lib/postgresql/data
    
volumes:
  pg-test-database: